- name: Install freeipa-client
  package:
    name: freeipa-client
    state: latest

- shell: credstash -r eu-west-1 get freeipa/system_user
  register: credstash_freeipa_output
  ignore_errors: yes

- file:
    path: /etc/resolv.conf
    state: absent

- file:
    src: /run/resolvconf/resolv.conf
    dest: /etc/resolv.conf
    owner: root
    group: root
    state: link

- name: Modify dhclient.conf to put freeipa nameserver and dns search on reboot to override AWS
  blockinfile:
    path: /etc/dhcp/dhclient.conf
    block: |
      supersede domain-name-servers 172.16.41.114, 172.16.40.49;
      supersede domain-search "access.common-pds.org eu-west-1.compute.internal";
      supersede domain-name "access.common-pds.org eu-west-1.compute.internal";

- name: renew dhcp
  command: dhclient

#- shell: ipa-client-install -d -U  -p admin -w {{ freeipa_system_user }}  --mkhomedir --ssh-trust-dns
#  args:
#    creates: /etc/sssd/sssd.conf

- name: Modify PAM common-session so that user home directory is created on first login
  lineinfile:
    dest: /etc/pam.d/common-session
    line: "session required pam_mkhomedir.so"
    insertbefore: ".end of pam-auth-update config"
    state: present
