es_major_version: 5.x
elk_version: 5.6.5
es_apt_key: https://artifacts.elastic.co/GPG-KEY-elasticsearch
es_apt_url: deb https://artifacts.elastic.co/packages/{{ es_major_version }}/apt stable main

kibana_user: kibana
kibana_group: kibana
kibana_version: "{{ elk_version }}"
kibana_server_port: "{{instance_port}}"
kibana_server_host: 0.0.0.0
kibana_enabled_on_boot: yes
kibana_elasticsearch_url: http://localhost:9200
kibana_instance: "{{instance_port}}"
