
- name: update
  apt:
    update_cache: yes
    
- name: Install software-properties-common
  apt:
    name: software-properties-common


- name: Upgrade
  apt:
    name: ansible

- name: Install ntp
  package:
    name: ntp

- name: Install python-minimal
  package:
    name: python-minimal

- name: Install python-pip
  package:
    name: python-pip

- name: Install python-setuptools
  package:
    name: python-setuptools

- name: Install python-dev
  package:
    name: python-dev

- name: Install build-essential
  package:
    name: build-essential

- name: Install libssl-dev
  package:
    name: libssl-dev

- name: Install libffi-dev
  package:
    name: libffi-dev

- name: Install screen
  package:
    name: screen

- name: Install nano
  package:
    name: nano

- name: Install traceroute
  package:
    name: traceroute

- name: Install iftop
  package:
    name: iftop

- name: Install tree
  package:
    name: tree

- name: Install htop
  package:
    name: htop

- name: Install ncdu
  package:
    name: ncdu

- name: Install freeipa-client
  package:
    name: freeipa-client

- pip:
    name: credstash

- name:  cleans the local repository of retrieved package files that can no longer be downloaded
  apt:
    autoclean: yes
- name: Remove dependencies that are no longer required
  apt:
    autoremove: yes
- name: Install snapd
  apt:
    name: snapd


- name: install AWS SSM agent using snap
  shell: snap install amazon-ssm-agent --classic
  args:
    creates: /snap/amazon-ssm-agent/current/amazon-ssm-agent
