- name: Modify dhclient.conf to put freeipa nameserver and dns search on reboot to override AWS
  blockinfile:
    path: /etc/dhcp/dhclient.conf
    block: |
      supersede domain-name-servers 172.16.41.114, 172.16.40.49;
      supersede domain-search "access.common-pds.org eu-west-1.compute.internal";
      supersede domain-name "access.common-pds.org eu-west-1.compute.internal";
    state: absent

  - name: renew dhcp
    command: dhclient
