# Install Filebeat

- shell: wget -qO - https://artifacts.elastic.co/GPG-KEY-elasticsearch | sudo apt-key add -
- shell: echo "deb https://artifacts.elastic.co/packages/6.x/apt stable main" | sudo tee -a /etc/apt/sources.list.d/elastic-6.x.list

- name: install Filebeat
  package:
    name: filebeat
    state: latest


- copy:
    src: files/filebeat-ubuntu.yml
    dest: /etc/filebeat/filebeat.yml
    owner: root
    group: root
    mode: 0600


- service:
    name: filebeat
    state: restarted
