---

- name: Test distribution
  assert:
    that: >
      ansible_os_family == "RedHat" or
      ansible_os_family == "Debian"
- name: Install sssd package
  package:
    name: "{{ sssd_pkg }}"
  notify:
    - Restart sssd
  tags:
    - sssd_pkg

- name: Configure sssd service
  template:
    src: sssd.conf.j2
    dest: /etc/sssd/sssd.conf
    mode: 0600
    owner: root
    group: root
  notify:
    - Restart sssd
  tags:
    - sssd_config

- name: Make sure sssd service is enabled
  service:
    name: sssd
    enabled: yes
  tags:
    - sssd_service

- name: Make sure sssd service is running
  service:
    name: sssd
    state: started
  register: sssd_service_started
  tags:
    - sssd_service
