filebeat.prospectors:
- type: log
  enabled: true
  paths:
    - /var/log/*/*.log
    - /var/log/*.log
    - /var/log/datadog/*.log
    - /var/log/syslog
    - /var/log/filebeat/filebeat
  exclude_files: []




#==========================  Modules configuration ============================
filebeat.modules:

#------------------------------- System Module -------------------------------
- module: system
  # Syslog
  syslog:
    enabled: true
    var.paths: ["/var/log/syslog*"]
  auth:
    enabled: true
    var.paths: ["/var/log/auth.log*"]

output.logstash:
  enabled: true
  hosts: ["internal-logstash-elb-1601667298.eu-west-1.elb.amazonaws.com:5044"]
  worker: 1
  index: 'filebeat'
